/*
# Fix Subscription Schema Types
- Ensures 'plans' table exists with BigInt ID.
- Fixes 'profiles.plan_id' to be BigInt to match 'plans.id'.
- Adds 'subscription_status' and 'payment_date'.
*/

-- 1. Ensure plans table exists (Safe check)
CREATE TABLE IF NOT EXISTS public.plans (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name text NOT NULL,
  price numeric NOT NULL,
  description text,
  features text[],
  created_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 2. Fix profiles table columns
DO $$ 
BEGIN
    -- Drop plan_id if it exists (to fix type mismatch from previous failed attempts)
    -- We drop it to recreate it with the correct type (BigInt)
    IF EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = 'profiles' AND column_name = 'plan_id') THEN
        ALTER TABLE public.profiles DROP COLUMN plan_id;
    END IF;

    -- Add plan_id as BIGINT referencing plans(id)
    ALTER TABLE public.profiles 
    ADD COLUMN plan_id bigint REFERENCES public.plans(id);

    -- Add subscription_status if missing
    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = 'profiles' AND column_name = 'subscription_status') THEN
        ALTER TABLE public.profiles ADD COLUMN subscription_status text DEFAULT 'inactive';
    END IF;

    -- Add payment_date if missing
    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = 'profiles' AND column_name = 'payment_date') THEN
        ALTER TABLE public.profiles ADD COLUMN payment_date timestamp with time zone;
    END IF;
END $$;

-- 3. Insert Default Plans (if table is empty) to ensure the UI has data
INSERT INTO public.plans (name, price, description, features)
SELECT 'Free', 0, 'For individuals starting out.', ARRAY['10 Generations/month', '1 Brand Voice', 'Basic Tone Analysis']
WHERE NOT EXISTS (SELECT 1 FROM public.plans WHERE name = 'Free');

INSERT INTO public.plans (name, price, description, features)
SELECT 'Pro', 29, 'For professionals and small teams.', ARRAY['100 Generations/month', '5 Brand Voices', 'Advanced Tone Analysis', 'Priority Support']
WHERE NOT EXISTS (SELECT 1 FROM public.plans WHERE name = 'Pro');

INSERT INTO public.plans (name, price, description, features)
SELECT 'Enterprise', 99, 'For large organizations.', ARRAY['Unlimited Generations', 'Unlimited Brands', 'Dedicated AI Model', '24/7 Support']
WHERE NOT EXISTS (SELECT 1 FROM public.plans WHERE name = 'Enterprise');
