/*
          # [Initial Schema Setup]
          This script establishes the foundational database structure for the Marketing AI platform.

          ## Query Description: [This migration creates all necessary tables for user profiles, subscriptions, content management, and administrative controls. It also configures Row Level Security (RLS) to protect user data and sets up a trigger to automatically create user profiles upon signup. This is a critical first step to making the application data-persistent. No existing data will be affected as this is the initial setup.]
          
          ## Metadata:
          - Schema-Category: ["Structural"]
          - Impact-Level: ["High"]
          - Requires-Backup: [false]
          - Reversible: [false]
          
          ## Structure Details:
          - Tables Created: profiles, plans, subscriptions, generated_content, brand_voices, coupons, api_keys, site_hero, site_features, site_testimonials, ai_providers, platform_settings
          - Triggers Created: on_auth_user_created
          - RLS Policies: Enabled and configured for all user-specific tables.
          
          ## Security Implications:
          - RLS Status: [Enabled]
          - Policy Changes: [Yes]
          - Auth Requirements: [Policies distinguish between anonymous, authenticated users, and admins.]
          
          ## Performance Impact:
          - Indexes: [Primary keys and foreign keys are indexed by default.]
          - Triggers: [A trigger is added to auth.users for profile creation.]
          - Estimated Impact: [Low, as this is the initial setup.]
          */

-- 1. PROFILES TABLE
-- Stores public user data and role.
CREATE TABLE public.profiles (
  id UUID NOT NULL PRIMARY KEY REFERENCES auth.users(id) ON DELETE CASCADE,
  full_name TEXT,
  avatar_url TEXT,
  company TEXT,
  role TEXT DEFAULT 'user',
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

COMMENT ON TABLE public.profiles IS 'Public user profiles, linked to auth.users.';

-- 2. PLANS TABLE
-- Stores subscription plan details.
CREATE TABLE public.plans (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  description TEXT,
  price NUMERIC,
  price_id TEXT, -- For Stripe integration
  features TEXT[]
);

COMMENT ON TABLE public.plans IS 'Defines the available subscription plans.';

-- 3. SUBSCRIPTIONS TABLE
-- Tracks user subscriptions.
CREATE TABLE public.subscriptions (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id UUID NOT NULL REFERENCES public.profiles(id) ON DELETE CASCADE,
  plan_id BIGINT NOT NULL REFERENCES public.plans(id) ON DELETE CASCADE,
  status TEXT, -- e.g., 'active', 'canceled', 'past_due'
  current_period_start TIMESTAMPTZ,
  current_period_end TIMESTAMPTZ
);

COMMENT ON TABLE public.subscriptions IS 'Manages user subscriptions to different plans.';

-- 4. GENERATED CONTENT TABLE
-- Stores all content created by users.
CREATE TABLE public.generated_content (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id UUID NOT NULL REFERENCES public.profiles(id) ON DELETE CASCADE,
  platform TEXT,
  text TEXT,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

COMMENT ON TABLE public.generated_content IS 'Stores all AI-generated content for users.';

-- 5. BRAND VOICES TABLE
-- Stores user-defined brand voice profiles.
CREATE TABLE public.brand_voices (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id UUID NOT NULL REFERENCES public.profiles(id) ON DELETE CASCADE,
  name TEXT NOT NULL,
  tone TEXT,
  keywords TEXT[],
  created_at TIMESTAMPTZ DEFAULT NOW()
);

COMMENT ON TABLE public.brand_voices IS 'User-defined brand voice profiles for content generation.';

-- 6. COUPONS TABLE
-- Stores promotional coupon codes.
CREATE TABLE public.coupons (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  code TEXT NOT NULL UNIQUE,
  discount_type TEXT NOT NULL, -- 'percentage' or 'fixed'
  discount_value NUMERIC NOT NULL,
  expires_at TIMESTAMPTZ,
  usage_limit INT,
  is_active BOOLEAN DEFAULT TRUE
);

COMMENT ON TABLE public.coupons IS 'Promotional codes for discounts.';

-- 7. API KEYS TABLE
-- Stores user-generated API keys.
CREATE TABLE public.api_keys (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id UUID NOT NULL REFERENCES public.profiles(id) ON DELETE CASCADE,
  name TEXT NOT NULL,
  key_hash TEXT NOT NULL,
  key_prefix TEXT NOT NULL,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  last_used_at TIMESTAMPTZ
);

COMMENT ON TABLE public.api_keys IS 'User-generated API keys for integrations.';

-- 8. SITE CONTENT TABLES
-- For admin-editable homepage content.
CREATE TABLE public.site_hero (
  id INT PRIMARY KEY DEFAULT 1,
  title TEXT,
  subtitle TEXT,
  CONSTRAINT single_row CHECK (id = 1)
);

CREATE TABLE public.site_features (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title TEXT,
  description TEXT,
  icon TEXT,
  sort_order INT
);

CREATE TABLE public.site_testimonials (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  text TEXT,
  author TEXT,
  role TEXT,
  sort_order INT
);

COMMENT ON TABLE public.site_hero IS 'Content for the homepage hero section (single row).';
COMMENT ON TABLE public.site_features IS 'Content for the homepage features section.';
COMMENT ON TABLE public.site_testimonials IS 'Content for the homepage testimonials section.';

-- 9. AI PROVIDERS TABLE
-- For managing different AI models.
CREATE TABLE public.ai_providers (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  api_key_env_var TEXT, -- e.g., 'HUGGINGFACE_API_KEY'
  model TEXT,
  cost_per_token NUMERIC,
  is_active BOOLEAN DEFAULT TRUE
);

COMMENT ON TABLE public.ai_providers IS 'Configuration for different AI service providers.';

-- 10. PLATFORM SETTINGS TABLE
-- Key-value store for global settings.
CREATE TABLE public.platform_settings (
  key TEXT PRIMARY KEY,
  value JSONB,
  description TEXT
);

COMMENT ON TABLE public.platform_settings IS 'Global key-value settings for the platform.';

-- SEED DATA for admin-managed tables
INSERT INTO public.plans (name, description, price, price_id, features) VALUES
('Free', 'For individuals starting out.', 0, 'price_free_tier', '{"10 generations/mo", "1 brand voice"}'),
('Pro', 'For professionals and small teams.', 29, 'price_pro_tier', '{"100 generations/mo", "5 brand voices", "Priority support"}'),
('Enterprise', 'For large organizations.', NULL, 'price_enterprise_tier', '{"Unlimited everything", "Dedicated AI model", "24/7 support"}');

INSERT INTO public.site_hero (id, title, subtitle) VALUES
(1, 'Generate Viral Social Media Content with AI', 'Stop guessing. Start growing. Our AI analyzes your brand''s voice to create posts, and scripts that resonate with your audience in any language.');

INSERT INTO public.site_features (title, description, icon, sort_order) VALUES
('Brand Voice Analysis', 'Import posts or link your Facebook page. Our AI learns your unique tone.', 'BarChart', 1),
('Multi-Platform Content', 'Get tailored content for Facebook, TikTok, and YouTube in one click.', 'Bot', 2),
('Multilingual Magic', 'Primary support for Arabic (RTL) and English. Reach a global audience.', 'Languages', 3),
('Video Scripts', 'Generate engaging 30-60 second video scripts for TikTok and YouTube Shorts.', 'Clapperboard', 4);

INSERT INTO public.site_testimonials (text, author, role, sort_order) VALUES
('"Marketing AI transformed our content strategy. Our engagement in Arabic has skyrocketed!"', 'Fatima Al-Jamil', 'Coffee Shop Owner', 1),
('"I save hours every week. The AI just gets my brand''s humor and style perfectly."', 'Youssef Hassan', 'Burger Shop Marketer', 2);

INSERT INTO public.ai_providers (name, model, is_active) VALUES
('OpenAI', 'gpt-4', true),
('Hugging Face', 'llama3', true),
('Anthropic', 'claude-3-sonnet', true),
('DeepSeek', 'deepseek-coder', false),
('Google', 'gemini-pro', false);

INSERT INTO public.platform_settings (key, value, description) VALUES
('maintenance_mode', '{"enabled": false}', 'Toggles maintenance mode for the entire site.');

-- SETUP RLS and POLICIES

-- Helper function to check for admin role
CREATE OR REPLACE FUNCTION public.is_admin()
RETURNS BOOLEAN AS $$
BEGIN
  RETURN EXISTS (
    SELECT 1 FROM public.profiles WHERE id = auth.uid() AND role = 'admin'
  );
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- 1. Profiles RLS
ALTER TABLE public.profiles ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Users can view all profiles." ON public.profiles FOR SELECT USING (true);
CREATE POLICY "Users can insert their own profile." ON public.profiles FOR INSERT WITH CHECK (auth.uid() = id);
CREATE POLICY "Users can update their own profile." ON public.profiles FOR UPDATE USING (auth.uid() = id);
CREATE POLICY "Admins can manage all profiles." ON public.profiles FOR ALL USING (public.is_admin()) WITH CHECK (public.is_admin());

-- 2. Subscriptions RLS
ALTER TABLE public.subscriptions ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Users can manage their own subscription." ON public.subscriptions FOR ALL USING (auth.uid() = user_id);
CREATE POLICY "Admins can manage all subscriptions." ON public.subscriptions FOR ALL USING (public.is_admin());

-- 3. Generated Content RLS
ALTER TABLE public.generated_content ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Users can manage their own content." ON public.generated_content FOR ALL USING (auth.uid() = user_id);
CREATE POLICY "Admins can manage all content." ON public.generated_content FOR ALL USING (public.is_admin());

-- 4. Brand Voices RLS
ALTER TABLE public.brand_voices ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Users can manage their own brand voices." ON public.brand_voices FOR ALL USING (auth.uid() = user_id);
CREATE POLICY "Admins can manage all brand voices." ON public.brand_voices FOR ALL USING (public.is_admin());

-- 5. API Keys RLS
ALTER TABLE public.api_keys ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Users can manage their own API keys." ON public.api_keys FOR ALL USING (auth.uid() = user_id);
CREATE POLICY "Admins can manage all API keys." ON public.api_keys FOR ALL USING (public.is_admin());

-- Admin-only tables (no RLS needed if access is restricted at the API level, but good practice)
ALTER TABLE public.plans ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Public can read plans." ON public.plans FOR SELECT USING (true);
CREATE POLICY "Admins can manage plans." ON public.plans FOR ALL USING (public.is_admin());

ALTER TABLE public.coupons ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Admins can manage coupons." ON public.coupons FOR ALL USING (public.is_admin());

ALTER TABLE public.site_hero ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Public can read hero." ON public.site_hero FOR SELECT USING (true);
CREATE POLICY "Admins can manage hero." ON public.site_hero FOR ALL USING (public.is_admin());

ALTER TABLE public.site_features ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Public can read features." ON public.site_features FOR SELECT USING (true);
CREATE POLICY "Admins can manage features." ON public.site_features FOR ALL USING (public.is_admin());

ALTER TABLE public.site_testimonials ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Public can read testimonials." ON public.site_testimonials FOR SELECT USING (true);
CREATE POLICY "Admins can manage testimonials." ON public.site_testimonials FOR ALL USING (public.is_admin());

ALTER TABLE public.ai_providers ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Admins can manage AI providers." ON public.ai_providers FOR ALL USING (public.is_admin());

ALTER TABLE public.platform_settings ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Admins can manage platform settings." ON public.platform_settings FOR ALL USING (public.is_admin());

-- TRIGGER to create a profile when a new user signs up
CREATE OR REPLACE FUNCTION public.handle_new_user()
RETURNS TRIGGER AS $$
BEGIN
  INSERT INTO public.profiles (id, role)
  VALUES (NEW.id, 'user');
  RETURN NEW;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

CREATE TRIGGER on_auth_user_created
  AFTER INSERT ON auth.users
  FOR EACH ROW EXECUTE FUNCTION public.handle_new_user();

-- STORAGE POLICIES for avatars
CREATE POLICY "Avatar images are publicly accessible."
  ON storage.objects FOR SELECT
  USING ( bucket_id = 'avatars' );

CREATE POLICY "Anyone can upload an avatar."
  ON storage.objects FOR INSERT
  WITH CHECK ( bucket_id = 'avatars' );

CREATE POLICY "Anyone can update their own avatar."
  ON storage.objects FOR UPDATE
  USING ( auth.uid() = owner )
  WITH CHECK ( bucket_id = 'avatars' );
